blank_issues_enabled: false
contact_links:
  - name: â“ Question
    url: https://help.nextcloud.com/
    about: I have a question â€¦
  - name: ğŸš¨ Report a security or privacy issue
    url: https://hackerone.com/nextcloud
    about: Report security and privacy related issues privately to the Nextcloud team, so we can coordinate the fix and release without potentially exposing all Nextcloud servers and users in the meantime.
  - name: ğŸš¨ æŠ¥å‘Šå®‰å…¨æˆ–éšç§é—®é¢˜
    url: https://hackerone.com/nextcloud
    about: è¯·ä»¥ç§å¯†æ–¹å¼å‘ Nextcloud å›¢é˜ŸæŠ¥å‘Šå®‰å…¨å’Œéšç§ç›¸å…³é—®é¢˜ï¼Œä»¥ä¾¿æˆ‘ä»¬èƒ½å¤Ÿåè°ƒä¿®å¤å·¥ä½œå¹¶å®‰æ’å‘å¸ƒè®¡åˆ’ï¼Œé¿å…åœ¨æ­¤æœŸé—´å¯èƒ½æš´éœ²æ‰€æœ‰ Nextcloud æœåŠ¡å™¨å’Œç”¨æˆ·çš„é£é™©ã€‚
