# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
#
# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Block unconventional commits

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

permissions:
  contents: read

concurrency:
  group: block-unconventional-commits-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  block-unconventional-commits:
    name: Block unconventional commits

    runs-on: ubuntu-latest-low

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: webiny/action-conventional-commits@faccb24fc2550dd15c0390d944379d2d8ed9690e # v1.3.1
        if: ${{ github.base_ref == 'main' }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: webiny/action-conventional-commits@faccb24fc2550dd15c0390d944379d2d8ed9690e # v1.3.1
        if: ${{ github.base_ref != 'main' }}
        with:
          allowed-commit-types: "fix,docs,style,refactor,test,build,perf,ci,chore,revert,merge" # Anything but "feat" https://github.com/webiny/action-conventional-commits/blob/8bc41ff4e7d423d56fa4905f6ff79209a78776c7/action.yml#L9C15-L9C85
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
